### ISSUE TITLE
"Converting circular structure to JSON" error

### ISSUE THREAD

**Issue by ewnd9** [parro-it/comws#4]
Hi, I tried to add [`electron-input-menu`](https://github.com/parro-it/electron-input-menu) to a project, but example code, when I clicked on `<img>` (somehow I thought menu for images was supported)

``` js
const inputMenu = require('electron-input-menu');
const context = require('electron-contextmenu-middleware');

context.use(inputMenu);

context.activate();
```

threw

``` js
Uncaught TypeError: context.run(...).then is not a function  index:12
```

So I tried to find out what `context.run` returns and why it doesn't have `then` function 

``` js
console.log(context.run({menu, elm, click}))
```

This code threw another error (the reason of weird stacktrace is webpack) 

```
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at step (http://localhost:8080/app.bundle.js:35536:90)
    at CoMws.run (http://localhost:8080/app.bundle.js:35571:13)
    at run (http://localhost:8080/app.bundle.js:35401:24)
    at HTMLBodyElement.onContextmenu (http://localhost:8080/app.bundle.js:35418:4)
```

which pointed to `comws` and `JSON.stringify` https://github.com/parro-it/comws/blob/64f3fc9927898a0033f82e4c63999e0f402d9e1a/index.js#L78

After I replace `JSON.stringify(ctx)` with just `ctx` there was no error

**Comment by parro-it** [comment]
Hi, thank you for your investigations!
I don't think the circular reference error you find on comws is related to this. 
You are probably getting a wrong `ctx` there.

Anyway, I put together a small gist example here: https://gist.github.com/parro-it/e03dfa1c8fb707454f773cebfeba6cfa.

When I run that, nothing happens clicking on the `img`, as expected.

Could you try this example too and see what happens ?

**Comment by parro-it** [comment]
Oh I forgot one thing: if you run the source with `debug` enabled, what you see logged on the line, after you removed the stringify instruction?

**Comment by ewnd9** [comment]
Gist works ok.

`JSON.stringify(ctx)`

```
comws running inputMenu with context: {"menu":[],"elm":{},"click":{"x":37,"y":45}} +0ms
```

for your image, mine throws the error

`ctx`

```
comws running inputMenu with context: [object Object] +0ms
```

for both.

Interesting part:

`console.log(ctx)` in electron devtools 

![image](https://cloud.githubusercontent.com/assets/1713789/14344619/44534c66-fcdb-11e5-94f4-16ebd20619dc.png)

shows that the 2nd argument is a dom element.

Maybe `JSON.stringify` should be replaced as it anyway shows misleading information (`"elm":{}` instead of indicating that it is a dom element)?

Also I reduced the problem in my project to react img tag with `ref` attribute (apparently circular dependency)

**Comment by parro-it** [comment]
> Maybe JSON.stringify should be replaced as it anyway shows misleading information ("elm":{} instead > of indicating that it is a dom element)?

Yes, you're right. Do you mind doing a PR?

> Also I reduced the problem in my project to react img tag with ref attribute (apparently circular dependency)

That's fine, I think that could be effectively solved by just replacing the JSON.stringify call?

One thing I don't understand is how you expect to use the input menu on a image tag? It's for copy the image to clipboard?

Please note that, even if you avoid the error, the menu should popup only for `input` and `textarea` tags. [See here](https://github.com/parro-it/electron-input-menu/blob/master/index.js#L32) how they are filtered.

**Comment by ewnd9** [comment]
> Yes, you're right. Do you mind doing a PR?

I could, but can't imagine replacement right now, only delete the call

> One thing I don't understand is how you expect to use the input menu on a image tag? It's for copy the image to clipboard?

I've hoped to see "Save image as..."  but now I see in [documentation](https://github.com/electron/electron/blob/master/docs/api/menu-item.md) it's not a predefined role. 

I think I'm going to make a pull request to `electron-input-menu` with adding such option

**Comment by parro-it** [comment]
> I could, but can't imagine replacement right now, only delete the call

Great! That's fine, just remove the `ctx` var from the log line...

>  I think I'm going to make a pull request to electron-input-menu with adding such option

Nope, I want it to remain focused just on inputs elements. 
But it would be beautiful if you start another module such as `electron-image-menu` just for images. You could use electron-input-menu as a template for the new module, and I could provide help if you need...

**Comment by ewnd9** [comment]
> Nope, I want it to remain focused just on inputs elements. 
> But it would be beautiful if you start another module such as electron-image-menu just for images. You could use electron-input-menu as a template for the new module, and I could provide help if you need...

Ok, no problem, thanks for offering help

**Comment by parro-it** [comment]
You're welcome 😃  Thank you for your help here!

**Comment by ewnd9** [comment]
I've released [`electron-image-menu`](https://github.com/ewnd9/electron-image-menu) :tada: 

Feel free to comment if anything could be improved

**Comment by parro-it** [comment]
Good work! I posted some comments on your commits with some suggestions...
I'll add a reference to your repo in `electron-contextmenu-middleware` readme
